### ISSUE TITLE
Android 10 not Showing Number

### ISSUE THREAD

**Issue by muhammed-amein** [flutter-try-catch/sim_card_info#1]
Hello @FadyFouad, When running your library in an Android 10 the other fields are returning the expected values correctly except the Number,

`simCardInfo: [{"carrierName": "ethio telecom","displayName": "ethio telecom","slotIndex": "0","number": "","countryIso": "et","countryPhonePrefix": "et"}]`

I have added these permissions in my XML file

```
 <uses-feature android:name="android.hardware.telephony" android:required="false"/>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
   <uses-permission android:name="android.permission.READ_PHONE_NUMBERS"/>
```

Would further explore why this is happening?

Best

**Comment by FadyFouad** [comment]
This might be related to a **conflict with another Flutter package**,
 possibly conflicting with the READ_PRIVILEGED_PHONE_STATE permission.
`Please check if there are any other Flutter packages in your project that might be causing this conflict. `

Starting from Android 10 (API level 29), the system doesn't provide direct access to the non-resettable device identifiers, such as the phone number of the device, unless the app has the READ_PRIVILEGED_PHONE_STATE permission.

Feel free to provide more details about your project setup or the packages you're using so we can further assist you.

**Comment by safvan-husain** [comment]
how can resolve this, is there any work around
