### ISSUE TITLE
Invalid json from method channel

### ISSUE THREAD

**Issue by safvan-husain** [flutter-try-catch/sim_card_info#2]
I/System.out( 3496): simCardInfo: [{"carrierName": "Android","displayName": "Android","slotIndex": "89014103211118510720","number": "+15555215554","countryIso": "us","countryPhonePrefix": "us",}]
E/flutter ( 3496): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected character (at character 160)
E/flutter ( 3496): ...","number": "+15555215554","countryIso": "us","countryPhonePrefix": "us",}]
E/flutter ( 3496):                                                                             ^
E/flutter ( 3496): 
E/flutter ( 3496): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
E/flutter ( 3496): #1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:907:13)
E/flutter ( 3496): #2      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
E/flutter ( 3496): #3      JsonDecoder.convert (dart:convert/json.dart:610:36)
E/flutter ( 3496): #4      JsonCodec.decode (dart:convert/json.dart:216:41)
E/flutter ( 3496): #5      MethodChannelSimCardInfo.getSimInfo (package:sim_card_info/sim_card_info_method_channel.dart:22:29)
E/flutter ( 3496): <asynchronous suspension>
E/flutter ( 3496): #6      SimServices.get (package:recovery_app/services/sim_services.dart:16:21)
E/flutter ( 3496): <asynchronous suspension>

**Comment by safvan-husain** [comment]
if anyone encounter this issue, 

use the following in pubspec to get this issue resolved version.

sim_card_info:
    git:
      url: https://github.com/safvan-husain/sim_card_info.git
      ref: 8e9b6b09beea6da1314be9be84bf921e082dc991

**Comment by FadyFouad** [comment]
> if anyone encounter this issue,
> 
> use the following in pubspec to get this issue resolved version.
> 
> sim_card_info: git: url: https://github.com/safvan-husain/sim_card_info.git ref: [8e9b6b0](https://github.com/flutter-try-catch/sim_card_info/commit/8e9b6b09beea6da1314be9be84bf921e082dc991)

 Thank you for sharing the solution for others who might encounter a similar issue.

**Comment by muhammed-amein** [comment]
@safvan-husain, Thanks alot, you saved us a lot, 

you too @FadyFouad thanks for this amazing package and your quick responses.
